insert into abilities values ('Ability_0', 'Lorem ipsum dolor sit amet.', 53);
insert into abilities values ('Ability_1', 'Lorem ipsum dolor sit amet.', 56);
insert into abilities values ('Ability_2', 'Lorem ipsum dolor sit amet.', 8);
insert into abilities (`name`, description) values ('Ability_3', 'Lorem ipsum dolor sit amet.');
insert into abilities values ('Ability_4', 'Lorem ipsum dolor sit amet.', 51);
insert into abilities values ('Ability_5', 'Lorem ipsum dolor sit amet.', 4);
insert into abilities values ('Ability_6', 'Lorem ipsum dolor sit amet.', 66);
insert into abilities (`name`, description) values ('Ability_7', 'Lorem ipsum dolor sit amet.');
insert into abilities (`name`, description) values ('Ability_8', 'Lorem ipsum dolor sit amet.');
insert into abilities values ('Ability_9', 'Lorem ipsum dolor sit amet.', 75);
insert into abilities values ('Ability_10', 'Lorem ipsum dolor sit amet.', 76);
insert into abilities values ('Ability_11', 'Lorem ipsum dolor sit amet.', 69);
insert into abilities values ('Ability_12', 'Lorem ipsum dolor sit amet.', 40);
insert into abilities (`name`, description) values ('Ability_13', 'Lorem ipsum dolor sit amet.');
insert into abilities values ('Ability_14', 'Lorem ipsum dolor sit amet.', 58);
insert into abilities values ('Ability_15', 'Lorem ipsum dolor sit amet.', 38);
insert into abilities values ('Ability_16', 'Lorem ipsum dolor sit amet.', 31);
insert into abilities values ('Ability_17', 'Lorem ipsum dolor sit amet.', 56);
insert into abilities values ('Ability_18', 'Lorem ipsum dolor sit amet.', 71);
insert into abilities values ('Ability_19', 'Lorem ipsum dolor sit amet.', 0);
insert into abilities values ('Ability_20', 'Lorem ipsum dolor sit amet.', 89);
insert into abilities values ('Ability_21', 'Lorem ipsum dolor sit amet.', 78);
insert into abilities values ('Ability_22', 'Lorem ipsum dolor sit amet.', 77);
insert into abilities values ('Ability_23', 'Lorem ipsum dolor sit amet.', 59);
insert into abilities values ('Ability_24', 'Lorem ipsum dolor sit amet.', 23);
